POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Some Chick in a Theatre (it's all a dream)",
    "author": "Clo Rissanpro",
    "url": "https://riss.co",
    "likes": 666
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "The Butt and Nothing But",
    "author": "Sir Mixalot",
    "url": "https://booty.butt",
    "likes": 100
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "69 Reasons to 69",
    "author": "Sum Singlelady",
    "url": "https://missigivings.shout",
    "likes": 5
}